name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select iOS Simulator
        id: select_device
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "device=$device" >> $GITHUB_OUTPUT

      - name: Build main app (elf)
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then \
            filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; \
          else \
            filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; \
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild clean build \
            -scheme elf \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=${{ steps.select_device.outputs.device }}"

      - name: Build elf_Kit for testing
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then \
            filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; \
          else \
            filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; \
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild clean build-for-testing \
            -scheme elf_Kit \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=${{ steps.select_device.outputs.device }}"

      - name: Run elf_Kit tests
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then \
            filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; \
          else \
            filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; \
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild test-without-building \
            -scheme elf_Kit \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=${{ steps.select_device.outputs.device }}"
